### ISSUE TITLE
Table on user approval shows empty colums

### ISSUE THREAD

**Issue by satunaite** [mantaskle/pharmacology-project#1]
#Description
After approving/removing new user registration, the table does not show buttons as supposed to, but the columns are still left empty - needs fixing on the front-end. 
![image](https://user-images.githubusercontent.com/43789014/56290278-7c651c80-612b-11e9-83c5-42a6d9402759.png)

**Comment by mantaskle** [comment]
#Fixed

Added an extra check for users approval table being empty
